name: Bump version and publish to NPM
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.7.1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: bump_version
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
    - name: Publish new version to npm
      run: |
         npm version $NEW_VERSION
         npm publish
      env:
         NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
         NEW_VERSION: ${{ steps.bump_version.outputs.new_tag }}
